### ISSUE TITLE
about Navigational status

### ISSUE THREAD

**Issue by lrlin5656** [ronzeiller/NMEA0183-AIS#1]
Thanks for your works. I want to have one input here. The Navigational status 0 is legal and it indicate "Under way using engine". Hence, the check statement of AddNavStatus() of "NMEA0183AISMessages.cpp" (line 385) should include the case 0. 

(NavStatus >= 0 && NavStatus <= 15 )? iTemp = NavStatus : iTemp = 15;

 Regards, Li-Ren

**Comment by ronzeiller** [comment]
Thank you Li-Ren!
Regards, Ronnie
