### ISSUE TITLE
buffer overrun tNMEA0183AISMsg

### ISSUE THREAD

**Issue by lsoltero** [ronzeiller/NMEA0183-AIS#2]
char buf[1];
  for(int i = countBits-1; i >= 0 ; i--) {
    sprintf(buf, "%d", (int) bset[i]);

sprintf writes 2 bytes since it terminates the string with a '0'.  it would be better to replace this with

char buf[2];
...
snprintf(buf, sizeof(buf), "%d", (int) bset[j]);

--luis

**Comment by ronzeiller** [comment]
Thank you Luis.
changed it according to your recommandations
