### ISSUE TITLE
tN2kAISTranceiverInfo was not declared in this scope

### ISSUE THREAD

**Issue by greenhouse69** [ronzeiller/NMEA0183-AIS#6]
When I try to compile the NMEA2000ToWiFiAsNMEA0183WithAIS example from the Arduino IDE, I get this error: 
Compilation error: 'tN2kAISTranceiverInfo' was not declared in this scope. 
Any suggestions?

**Comment by greenhouse69** [comment]
Error in N2kDataToNMEA0183.cpp you should change tN2kAISTranceiverInfo _AISinfo; to tN2kAISTransceiverInformation _AISinfo; Now it works!

**Comment by ronzeiller** [comment]
@greenhouse69 there is more than just renaming tN2kAISTransceiverInformation...
Fixed Code to work with [@ttlappalainen](https://github.com/ttlappalainen/NMEA2000) NMEA2000 v4.21.3
